print("*"*60)
print("                  My Profile        ")
print("*"*60)
print("Name :-   Krishna Yadav")
print("Age :-   19")
print("Gender  : Male")
print("Studying :-  Bsc in Computer Science")
print("Phone No. :-  9653258031")
print("Hobbies :-  Tracking, Coding, Farming, Exploring")
print("Skills  : Python, Java, HTML, SQL")
print("City :-  Mumbai")
print("*"*60) 
